Import('env')

import os

commons_path = os.getcwd() + '/../../'

env.Append(
    CPPPATH = ['#', commons_path, '/usr/include', '/usr/local/include', commons_path ],
    LIBPATH = ['/usr/lib', '/usr/local/lib' ],
    LIBS = ['check', 'curl', 'm', 'z'],
    LINKFLAGS = [ '-openmp' ]
)

check_linked_list = env.Program('linked_list.test', 
                    	         source = ['linked_list_test.c', 
				           '%s/containers/linked_list.o' % commons_path
                                          ]
                                )
