Import('formats_env')

penv = formats_env.Clone()
penv['CFLAGS'] += ' -D_XOPEN_SOURCE=600'

formats_env['objects'] += penv.Object(source = [Glob('region/*.c'), Glob('variant/*.c')])

region_test = SConscript("region/test/SConscript", exports = ['penv'] )
