# This SConstruct does nothing more than load the SConscript in this dir
# The Environment() is created in the SConstruct script
# This dir can be built standalone by executing scons here, or together
# by executing scons in the parent directory

#Compiler configure
debug = int(ARGUMENTS.get('debug', '0'))
compiler = ARGUMENTS.get('compiler', 'gcc')

#Paths
system_include = '/usr/include'
system_libpath = '/usr/lib'

build_tools = ['default']


#Set environment
env = Environment(
        tools = build_tools,
        CFLAGS = ' -Wall -std=c99 -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_GNU_SOURCE -D_REENTRANT ',
        CPPPATH = ['.', '#', system_include, '%s/libxml2' % system_include],
        LIBPATH = [system_libpath],
		    LINKFLAGS = [],
      	LIBS = ['xml2', 'm', 'z'])

if compiler == 'icc':
	env['tools'] += ['intelc']
	env['CFLAGS'] += ' -msse4.2 -openmp '
	env['LIBS'] += ['irc']
	env['LINKFLAGS'] +=  ['-openmp']
else:
	env['CFLAGS'] += ' -fopenmp '
	env['LINKFLAGS'] += ['-fopenmp']

env['objects'] = []

env.Decider('MD5-timestamp')

#if debug == 1:

#        env['CFLAGS'] += '-O0 -g'
#else:
#        env['CFLAGS'] += '-O3 -g'


#Targets
SConscript('SConscript', exports = ['env', 'debug', 'compiler'])
