Import('hpg_cpp_env', 'debug', 'compiler')

env = hpg_cpp_env

hpg_cpp_env['objects'] = hpg_cpp_env.Object([ 
                                             "abort_error_policy.cpp",
                                             "meta_entry.cpp", 
                                             "parsing_state.cpp",
                                             "record.cpp",
                                             "report_error_policy.cpp",
                                             "source.cpp",
                                             "store_parse_policy.cpp"
                                            ])

# Generate application and libraries using C++ source files
hpg_cpp_env.Program("vcf_validator.out", hpg_cpp_env['objects'] + [ "main.cpp" ])

