import os

Import('env', 'debug', 'compiler')

# Initialize environment
bioenv = env.Clone()
bioenv.Decider('MD5-timestamp')

for dir in os.getenv('CPATH').split(':'):
    env.Append(CPPPATH=[dir])

for dir in os.getenv('LIBRARY_PATH').split(':'):
    env.Append(LIBPATH=[dir])

# Debug mode
if debug == 1:
    bioenv['CFLAGS'] += ' -O0 -g'
else:
    bioenv['CFLAGS'] += ' -O3 -g'

bioenv['objects'] = []

# Targets
SConscript(['bioformats/SConscript',], exports = ['bioenv'])
SConscript(['aligners/SConscript',], exports = ['bioenv'])

bioenv.Library('bioinfo', bioenv['objects'])

