import os
 
Import('env', 'compiler', 'debug')

# Initialize environment
bioenv = env.Clone()
bioenv.Decider('MD5-timestamp')

# Debug mode
if debug == 1:
    bioenv['CFLAGS'] += ' -O0 -g'
else:
    bioenv['CFLAGS'] += ' -O3 '

bioenv['objects'] = []

# Targets
SConscript(['bioformats/SConscript',], exports = ['bioenv', 'compiler', 'debug'])
SConscript(['aligners/SConscript',], exports = ['bioenv', 'compiler', 'debug'])

bioenv.Library('bioinfo', bioenv['objects'])

