/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.c: En la función ‘convert_to_quality_string_length’:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.c:487: aviso: la función devuelve la dirección de una variable local
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.c: En la función ‘convert_to_quality_string’:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.c:498: aviso: la función devuelve la dirección de una variable local
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/bam_file.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/bam_file.h:8:14: aviso: elementos extra al final de la directiva #ifdef
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/bam_file.h:214:14: aviso: elementos extra al final de la directiva #ifdef
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/bam_file.c:199:14: aviso: elementos extra al final de la directiva #ifdef
array_list.c: En la función ‘array_list_swap’:
array_list.c:380: aviso: la inicialización crea un entero desde un puntero sin una conversión
fastq_batch_reader.c: En la función ‘fastq_batch_reader_single’:
fastq_batch_reader.c:61: aviso: declaración implícita de la función ‘omp_get_thread_num’
En el fichero incluído de bwt.h:18,
                 de bwt.c:1:
BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de bwt.h:16,
                 de bwt.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de bwt.h:18,
                 de bwt.c:1:
BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de bwt.h:16,
                 de bwt.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
bwt.c: En la función ‘read_cals_new’:
bwt.c:173: aviso: la asignación descarta los calificadores del tipo del destino del puntero
bwt.c: En la función ‘read_cals_free’:
bwt.c:180: aviso: se pasa el argumento 2 de ‘array_list_free’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../common-libs/containers/array_list.h:65: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct cal_t *)’
bwt.c: En la función ‘bwt_generate_index_files’:
bwt.c:382: aviso: declaración implícita de la función ‘calculateBWT’
bwt.c:393: aviso: declaración implícita de la función ‘calculateC’
bwt.c:394: aviso: declaración implícita de la función ‘calculateO’
bwt.c:410: aviso: declaración implícita de la función ‘calculateR’
bwt.c:415: aviso: declaración implícita de la función ‘calculateSRcomp’
BW_io.c: En la función ‘load_exome_file’:
BW_io.c:686: aviso: la inicialización crea un entero desde un puntero sin una conversión
En el fichero incluído de bwt.h:18,
                 de test-preprocess.c:1:
BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de bwt.h:16,
                 de test-preprocess.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de bwt.h:18,
                 de test-preprocess.c:1:
BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de bwt.h:16,
                 de test-preprocess.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de bwt.h:18,
                 de test-search-cpu.c:4:
BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de bwt.h:16,
                 de test-search-cpu.c:4:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de bwt.h:18,
                 de test-search-cpu.c:4:
BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de bwt.h:16,
                 de test-search-cpu.c:4:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/../../../common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
test-search-cpu.c: En la función ‘main’:
test-search-cpu.c:53: aviso: declaración implícita de la función ‘bwt_map_exact_seed’
hpg_sw_bench.c: En la función ‘run_emboss’:
hpg_sw_bench.c:273: aviso: declaración implícita de la función ‘omp_set_num_threads’
hpg_sw_bench.c:309: aviso: declaración implícita de la función ‘omp_get_thread_num’
fastq_batch_reader.c: En la función ‘fastq_batch_reader_single’:
fastq_batch_reader.c:61: aviso: declaración implícita de la función ‘omp_get_thread_num’
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de main.c:17:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/fastq/fastq_file.h:8,
                 de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/fastq/fastq_batch_reader.h:11,
                 de main.c:12:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de main.c:17:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/fastq/fastq_file.h:8,
                 de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/fastq/fastq_batch_reader.h:11,
                 de main.c:12:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de batch_writer.h:17,
                 de main.c:19:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/bam_file.h:8:14: aviso: elementos extra al final de la directiva #ifdef
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/bam_file.h:214:14: aviso: elementos extra al final de la directiva #ifdef
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/sse.h:6,
                 de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/smith_waterman.h:8,
                 de sw_server.h:13,
                 de batch_writer.h:21,
                 de main.c:19:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/macros.h:12:1: aviso: se redefinió "MAX"
En el fichero incluído de buffers.h:8,
                 de main.c:17:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:25:1: aviso: esta es la ubicación de la definición previa
main.c: En la función ‘main’:
main.c:246: aviso: declaración implícita de la función ‘run_dna_aligner’
main.c: En el nivel principal:
main.c:296: aviso: tipos en conflicto para ‘run_dna_aligner’
main.c:246: nota: la declaración implícita previa de ‘run_dna_aligner’ estaba aquí
main.c: En la función ‘run_rna_aligner’:
main.c:460: aviso: se pasa el argumento 1 de ‘init_allocate_splice_elements’ desde un tipo de puntero incompatible
rna_splice.h:129: nota: se esperaba ‘struct allocate_splice_elements_t *’ pero el argumento es de tipo ‘struct allocate_splice_elements_t (*)[30]’
main.c:507: aviso: se pasa el argumento 2 de ‘rna_server_omp_smith_waterman’ desde un tipo de puntero incompatible
rna_server.h:86: nota: se esperaba ‘struct allocate_splice_elements_t *’ pero el argumento es de tipo ‘struct allocate_splice_elements_t (*)[30]’
main.c:510: aviso: se pasa el argumento 1 de ‘process_and_free_chromosome_avls’ desde un tipo de puntero incompatible
rna_splice.h:186: nota: se esperaba ‘struct allocate_splice_elements_t *’ pero el argumento es de tipo ‘struct allocate_splice_elements_t (*)[30]’
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/sse.h:6,
                 de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/smith_waterman.h:8,
                 de sw.h:15,
                 de sw.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/macros.h:22:1: aviso: se redefinió "FLT_MAX"
En el fichero incluído de sw.h:6,
                 de sw.c:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/include/float.h:104:1: aviso: esta es la ubicación de la definición previa
sw.c: En la función ‘smith_waterman_simd2’:
sw.c:270: aviso: inicialización desde un tipo de puntero incompatible
sw.c:271: aviso: inicialización desde un tipo de puntero incompatible
sw.c:405: aviso: asignación desde un tipo de puntero incompatible
sw.c:506: aviso: asignación desde un tipo de puntero incompatible
sw.c: En la función ‘smith_waterman_simd’:
sw.c:625: aviso: declaración implícita de la función ‘reallocate_memory’
sw.c: En la función ‘saveCharMatrixByIndex’:
sw.c:831: aviso: asignación desde un tipo de puntero incompatible
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de sw_server.h:16,
                 de rna_server.h:6,
                 de rna_server.c:3:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de sw_server.h:9,
                 de rna_server.h:6,
                 de rna_server.c:3:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de sw_server.h:16,
                 de rna_server.h:6,
                 de rna_server.c:3:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de sw_server.h:9,
                 de rna_server.h:6,
                 de rna_server.c:3:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de buffers.h:8,
                 de sw_server.h:16,
                 de rna_server.h:6,
                 de rna_server.c:3:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:25:1: aviso: se redefinió "MAX"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/sse.h:6,
                 de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/smith_waterman.h:8,
                 de sw_server.h:13,
                 de rna_server.h:6,
                 de rna_server.c:3:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/macros.h:12:1: aviso: esta es la ubicación de la definición previa
rna_server.c: En la función ‘rna_server_omp_smith_waterman’:
rna_server.c:1208: aviso: declaración implícita de la función ‘alignments_filter’
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de rna_splice.h:11,
                 de rna_splice.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de buffers.h:7,
                 de rna_splice.h:11,
                 de rna_splice.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de rna_splice.h:11,
                 de rna_splice.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de buffers.h:7,
                 de rna_splice.h:11,
                 de rna_splice.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
rna_splice.c: En la función ‘allocate_new_splice’:
rna_splice.c:109: aviso: el paso del argumento 2 de ‘cp_avltree_get’ crea un puntero desde un entero sin una conversión
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/cprops/avl.h:116: nota: se esperaba ‘void *’ pero el argumento es de tipo ‘unsigned int’
rna_splice.c:112: aviso: el paso del argumento 2 de ‘cp_avltree_insert’ crea un puntero desde un entero sin una conversión
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/cprops/avl.h:112: nota: se esperaba ‘void *’ pero el argumento es de tipo ‘unsigned int’
rna_splice.c:112: aviso: el paso del argumento 3 de ‘cp_avltree_insert’ crea un puntero desde un entero sin una conversión
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/cprops/avl.h:112: nota: se esperaba ‘void *’ pero el argumento es de tipo ‘unsigned int’
rna_splice.c: En la función ‘process_avlnode_ends_in_order’:
rna_splice.c:185: aviso: deferenciando el puntero ‘void *’
rna_splice.c:187: aviso: deferenciando el puntero ‘void *’
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de bwt_server.h:7,
                 de bwt_server_cpu.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de bwt_server.h:4,
                 de bwt_server_cpu.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de bwt_server.h:7,
                 de bwt_server_cpu.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de bwt_server.h:4,
                 de bwt_server_cpu.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
bwt_server_cpu.c: En la función ‘bwt_server_cpu’:
bwt_server_cpu.c:33: aviso: declaración implícita de la función ‘bwt_map_inexact_batch’
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de region_seeker.h:8,
                 de region_seeker.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de buffers.h:7,
                 de region_seeker.h:8,
                 de region_seeker.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de region_seeker.h:8,
                 de region_seeker.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de buffers.h:7,
                 de region_seeker.h:8,
                 de region_seeker.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
region_seeker.c: En la función ‘region_seeker_server’:
region_seeker.c:56: aviso: declaración implícita de la función ‘bwt_map_exact_seeds_seq’
region_seeker.c: En la función ‘apply_seeding’:
region_seeker.c:116: aviso: asignación desde un tipo de puntero incompatible
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de cal_seeker.h:4,
                 de cal_seeker.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de buffers.h:7,
                 de cal_seeker.h:4,
                 de cal_seeker.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de cal_seeker.h:4,
                 de cal_seeker.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de buffers.h:7,
                 de cal_seeker.h:4,
                 de cal_seeker.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
cal_seeker.c: En la función ‘cal_seeker_server’:
cal_seeker.c:60: aviso: declaración implícita de la función ‘bwt_generate_cal_list_linkedlist’
cal_seeker.c:106: aviso: se pasa el argumento 2 de ‘array_list_free’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/containers/array_list.h:65: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct cal_t *)’
cal_seeker.c: En la función ‘apply_caling’:
cal_seeker.c:217: aviso: se pasa el argumento 2 de ‘array_list_free’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/containers/array_list.h:65: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct region_t *)’
cal_seeker.c:224: aviso: se pasa el argumento 2 de ‘array_list_clear’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/containers/array_list.h:77: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct region_t *)’
cal_seeker.c:225: aviso: se pasa el argumento 2 de ‘array_list_clear’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/containers/array_list.h:77: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct cal_t *)’
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de pair_server.h:13,
                 de pair_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de pair_server.h:9,
                 de pair_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de pair_server.h:13,
                 de pair_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de pair_server.h:9,
                 de pair_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de sw_server.h:16,
                 de sw_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de sw_server.h:9,
                 de sw_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de sw_server.h:16,
                 de sw_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de sw_server.h:9,
                 de sw_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de buffers.h:8,
                 de sw_server.h:16,
                 de sw_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:25:1: aviso: se redefinió "MAX"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/sse.h:6,
                 de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/smith_waterman.h:8,
                 de sw_server.h:13,
                 de sw_server.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/macros.h:12:1: aviso: esta es la ubicación de la definición previa
sw_server.c: En la función ‘apply_sw’:
sw_server.c:474: aviso: se pasa el argumento 2 de ‘array_list_free’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/containers/array_list.h:65: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct cal_t *)’
En el fichero incluído de batch_writer.h:17,
                 de batch_writer.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/bam_file.h:8:14: aviso: elementos extra al final de la directiva #ifdef
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/bam_file.h:214:14: aviso: elementos extra al final de la directiva #ifdef
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de batch_writer.h:19,
                 de batch_writer.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de batch_writer.h:11,
                 de batch_writer.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de batch_writer.h:19,
                 de batch_writer.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de batch_writer.h:11,
                 de batch_writer.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/sse.h:6,
                 de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/smith_waterman.h:8,
                 de sw_server.h:13,
                 de batch_writer.h:21,
                 de batch_writer.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/macros.h:12:1: aviso: se redefinió "MAX"
En el fichero incluído de buffers.h:8,
                 de batch_writer.h:19,
                 de batch_writer.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:25:1: aviso: esta es la ubicación de la definición previa
batch_writer.c: En la función ‘batch_writer2’:
batch_writer.c:325: aviso: se pasa el argumento 6 de ‘generate_cigar_str’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:287: nota: se esperaba ‘short int *’ pero el argumento es de tipo ‘size_t *’
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de batch_aligner.h:13,
                 de batch_aligner.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de batch_aligner.h:9,
                 de batch_aligner.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de batch_aligner.h:13,
                 de batch_aligner.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de batch_aligner.h:9,
                 de batch_aligner.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/sse.h:6,
                 de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/smith_waterman.h:8,
                 de sw_server.h:13,
                 de batch_aligner.h:19,
                 de batch_aligner.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/sw/macros.h:12:1: aviso: se redefinió "MAX"
En el fichero incluído de buffers.h:8,
                 de batch_aligner.h:13,
                 de batch_aligner.c:1:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:25:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de buffers.c:7:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:202:1: aviso: se redefinió "tic"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de buffers.h:7,
                 de buffers.c:7:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:67:1: aviso: esta es la ubicación de la definición previa
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de buffers.c:7:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:207:1: aviso: se redefinió "toc"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/bioformats/bam-sam/alignment.h:8,
                 de buffers.h:7,
                 de buffers.c:7:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/commons/commons.h:72:1: aviso: esta es la ubicación de la definición previa
buffers.c:9:1: aviso: se redefinió "MAXLINE"
En el fichero incluído de /home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/bwt.h:18,
                 de buffers.h:8,
                 de buffers.c:7:
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/bioinfo-libs/aligners/bwt/BW_io.h:43:1: aviso: esta es la ubicación de la definición previa
buffers.c: En la función ‘region_batch_free’:
buffers.c:20: aviso: se pasa el argumento 2 de ‘array_list_free’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/containers/array_list.h:65: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct region_t *)’
buffers.c: En la función ‘sw_batch_free’:
buffers.c:44: aviso: se pasa el argumento 2 de ‘array_list_free’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/containers/array_list.h:65: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct cal_t *)’
buffers.c: En la función ‘cal_batch_free’:
buffers.c:121: aviso: se pasa el argumento 2 de ‘array_list_free’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/common-libs/containers/array_list.h:65: nota: se esperaba ‘void (*)(void *)’ pero el argumento es de tipo ‘void (*)(struct region_t *)’
timing.c: En la función ‘timing_new’:
timing.c:27: aviso: declaración implícita de la función ‘calloc’
timing.c:27: aviso: declaración implícita incompatible de la función interna ‘calloc’
timing.c:41: aviso: declaración implícita de la función ‘strdup’
timing.c:41: aviso: la asignación crea un puntero desde un entero sin una conversión
timing.c: En la función ‘timing_free’:
timing.c:59: aviso: declaración implícita de la función ‘free’
timing.c:59: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:61: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:62: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:63: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:66: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:68: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:69: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:70: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:72: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:73: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c:75: aviso: declaración implícita incompatible de la función interna ‘free’
timing.c: En la función ‘timing_display’:
timing.c:99: aviso: declaración implícita de la función ‘printf’
timing.c:99: aviso: declaración implícita incompatible de la función interna ‘printf’
genome.c:12: aviso: el elemento inicializador no es una constante
genome.c:12: aviso: (cerca de la inicialización de ‘TOTAL_CODES’)
genome.c:12: aviso: el elemento inicializador no es una constante
genome.c:12: aviso: (cerca de la inicialización de ‘TOTAL_CODES’)
genome.c: En la función ‘load_hasthable_codes’:
genome.c:163: aviso: se pasa el argumento 3 de ‘cp_hashtable_create’ desde un tipo de puntero incompatible
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/cprops/hashtable.h:283: nota: se esperaba ‘cp_compare_fn’ pero el argumento es de tipo ‘int (*)(const char *, const char *)’
genome.c:180: aviso: el paso del argumento 3 de ‘cp_hashtable_put’ crea un puntero desde un entero sin una conversión
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/cprops/hashtable.h:477: nota: se esperaba ‘void *’ pero el argumento es de tipo ‘unsigned char’
genome.c:193: aviso: el paso del argumento 3 de ‘cp_hashtable_put’ crea un puntero desde un entero sin una conversión
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/cprops/hashtable.h:477: nota: se esperaba ‘void *’ pero el argumento es de tipo ‘unsigned char’
genome.c:203: aviso: el paso del argumento 3 de ‘cp_hashtable_put’ crea un puntero desde un entero sin una conversión
/home/hmartinez/appl/bioinfo-c/hpg-aligner/lib/cprops/hashtable.h:477: nota: se esperaba ‘void *’ pero el argumento es de tipo ‘unsigned char’
genome.c: En la función ‘code_binary_file_generator’:
genome.c:319: aviso: conversión de puntero a entero de tamaño diferente
genome.c:334: aviso: conversión de puntero a entero de tamaño diferente
statistics.c: En la función ‘statistics_new’:
statistics.c:7: aviso: declaración implícita de la función ‘calloc’
statistics.c:7: aviso: declaración implícita incompatible de la función interna ‘calloc’
statistics.c:20: aviso: declaración implícita de la función ‘strdup’
statistics.c:20: aviso: la asignación crea un puntero desde un entero sin una conversión
statistics.c:26: aviso: la asignación crea un puntero desde un entero sin una conversión
statistics.c: En la función ‘statistics_free’:
statistics.c:35: aviso: declaración implícita de la función ‘free’
statistics.c:35: aviso: declaración implícita incompatible de la función interna ‘free’
statistics.c:38: aviso: declaración implícita incompatible de la función interna ‘free’
