import os
Import('debug', 'compiler')

if compiler == 'icc':
   env = Environment(tools = [ 'default', 'intelc' ],
                     CFLAGS = '-Wall -std=c99 -openmp -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_REENTRANT ',
		                 LINKFLAGS = ['openmp'],
                     LIBS = ['gsl', 'irc' ], 
                     CPPPATH = [ '.', 'data' ])
else:
   env = Environment(tools = [ 'default' ],
                     CFLAGS = '-Wall -std=c99 -fopenmp -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_REENTRANT ',
		                 LINKFLAGS = ['fopenmp'],
                     LIBS = ['gsl'], 
                     CPPPATH = [ '.', 'data' ])

if os.environ.has_key('CPATH'):
    for dir in os.getenv('CPATH').split(':'):
        env.Append(CPPPATH=[dir])

env.Decider('MD5-timestamp')

if debug == 1:
    env['CFLAGS'] += ' -O0 -g'
else:
    env['CFLAGS'] += ' -O3 -g'


# Targets
algebra_obj = env.Object(Glob('algebra/*.c'))
data_obj = env.Object(Glob('data/*.c'))
stats_obj = env.Object(Glob('stats/*.c'))
utils_obj = env.Object('math_utils.c')

env.Library('hpgmath', algebra_obj + data_obj + stats_obj + utils_obj)
