import os

Import('penv')

libhpg_path = os.getcwd() + '/../../../../build/'


env = penv.Clone()
env.Append(
    LIBPATH = ['/usr/lib', '/usr/local/lib', '#libs', libhpg_path],
    LIBS = [ 'check', 'curl', 'dl', 'm', 'gsl', 'gslcblas', 'rt', 'z' ],
    LINKFLAGS = ['-fopenmp' ]
)


filters = env.Program('filters_vcf.test', 
             source = ['test_vcf_filters.c', 
                               "%s/libhpg.a" % libhpg_path
                      ]
           )

stats = env.Program('stats_vcf.test', 
             source = ['test_stats.c', 
                               "%s/libhpg.a" % libhpg_path
                      ]
           )
