import os

Import('penv')

bioformats_path = os.getcwd() + '/../../../bioformats/'
commons_path = os.getcwd() + '/../../../commons/'
containers_path = os.getcwd() + '/../../../containers/'

env = penv.Clone()
env.Append(
    LIBPATH = ['/usr/lib', '/usr/local/lib', '#libs', commons_path , containers_path, bioformats_path],
    LIBS = [ 'check', 'common', 'curl', 'dl', 'm', 'gsl', 'gslcblas', 'rt', 'z' ],
    LINKFLAGS = ['-fopenmp' ]
)


filters = env.Program('filters_vcf.test', 
             source = ['test_vcf_filters.c', 
                               "%s/libcommon.a" % commons_path,
                               "%s/libbioformats.a" % bioformats_path,
                               "%s/libcontainers.a" % containers_path
                      ]
           )

stats = env.Program('stats_vcf.test', 
             source = ['test_stats.c', 
                               "%s/libcommon.a" % commons_path,
                               "%s/libbioformats.a" % bioformats_path,
                               "%s/libcontainers.a" % containers_path
                      ]
           )
