import os

Import('penv')

bioinfo_path = os.getcwd() + '/../../../'
commons_path = os.getcwd() + '/../../../../common-libs/'

env = penv.Clone()
env.Append(
    LIBPATH = ['/usr/lib', '/usr/local/lib', '#libs', commons_path ],
    LIBS = [ 'check', 'common', 'curl', 'dl', 'm', 'gsl', 'gslcblas', 'rt', 'z' ],
    LINKFLAGS = ['-fopenmp' ]
)


filters = env.Program('filters_vcf.test', 
             source = ['test_vcf_filters.c', 
                       "%s/libcommon.a" % commons_path,
                       "%s/libbioinfo.a" % bioinfo_path
                      ]
           )

stats = env.Program('stats_vcf.test', 
             source = ['test_stats.c', 
                       "%s/libcommon.a" % commons_path,
                       "%s/libbioinfo.a" % bioinfo_path
                      ]
           )
