Import('penv')

bioinfo_path = "#"
commons_path = "#../common-libs"
math_path = "#../math"

env = Environment(CFLAGS = '-std=c99 -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -fopenmp',
                  CPPPATH = ['#', '/usr/include', '/usr/local/include', bioinfo_path, commons_path, math_path ],
                  LIBPATH = ['/usr/lib', '/usr/local/lib', '#libs', '#libs/common-libs/', commons_path ],
                  LIBS = ['check', 'common', 'cprops', 'curl', 'm', 'z'],
                  LINKFLAGS = ['-fopenmp']
                  )

filters = env.Program('filters_vcf.test', 
             source = ['test_vcf_filters.c', 
                       Glob('#src/*.o'), Glob('#bioformats/vcf/*.o'),
                       "%s/libcommon.a" % commons_path,
                       "%s/bioformats/libbioformats.a" % bioinfo_path,
                       "%s/libhpgmath.a" % math_path
                      ]
           )

regions = env.Program('parse_regions_vcf.test', 
             source = ['test_parse_regions.c', 
                       Glob('#src/*.o'), Glob('#bioformats/vcf/*.o'),
                       "%s/libcommon.a" % commons_path,
                       "%s/bioformats/libbioformats.a" % bioinfo_path,
                       "%s/libhpgmath.a" % math_path
                      ]
           )

stats = env.Program('stats_vcf.test', 
             source = ['test_stats.c', 
                       Glob('#src/*.o'), Glob('#bioformats/vcf/*.o'),
                       "%s/libcommon.a" % commons_path,
                       "%s/bioformats/libbioformats.a" % bioinfo_path,
                       "%s/libhpgmath.a" % math_path
                      ]
           )
