import os

Import('env')

formats_env = env.Clone()
formats_env['objects'] = []


# Targets
formats = ['family', 'fastq', 'bam', 'gff', 'ped', 'features', 'vcf', 'db']

for dir in formats:
    SConscript(os.path.join(dir, 'SConscript'), exports = ['env', 'formats_env'])

formats_env.Library('bioformats', formats_env['objects'])

env['objects'] += formats_env['objects']

# Should traverse the tree and get the *.c files
#formats_env.SharedLibrary('bioformats', formats_env['objects'])

