import os

Import('bioenv', 'compiler', 'debug')

aligners_env = bioenv.Clone()
aligners_env['objects'] = []

# Targets
aligners = ['bwt', 'sw']

for dir in aligners:
    SConscript(os.path.join(dir, 'SConscript'), exports = ['bioenv', 'aligners_env', 'compiler', 'debug'])

aligners_env.Library('aligners', aligners_env['objects'])

bioenv['objects'] += aligners_env['objects']

# Should traverse the tree and get the *.c files
#aligners_env.SharedLibrary('aligners', aligners_env['objects'])

