import os

Import('env', 'compiler', 'debug')

# Initialize environment
aligners_env = env.Clone()
aligners_env['objects'] = []

if debug == 1:
    aligners_env['CFLAGS'] += ' -O0 -g'
else:
    aligners_env['CFLAGS'] += ' -O3 '


# Targets
aligners = ['bwt', 'sw']

for dir in aligners:
    SConscript(os.path.join(dir, 'SConscript'), exports = ['env', 'aligners_env', 'compiler', 'debug'])

env['objects'] += aligners_env['objects']

# Should traverse the tree and get the *.c files
#aligners_env.SharedLibrary('aligners', aligners_env['objects'])

