import os

Import('containersenv')

containers_path = os.getcwd() + '/../'

#env.Append(
#    CPPPATH = ['#', containers_path, '/usr/include', '/usr/local/include', containers_path ],
#    LIBPATH = ['/usr/lib', '/usr/local/lib' ],
#    LIBS = ['check', 'curl', 'm', 'z'],
#    LINKFLAGS = [ '-openmp' ]
#)

containerstest = containersenv.Clone()
containerstest['CPPPATH'] += [containers_path]
containerstest['LIBS'] += ['check', 'm', 'rt']

print "containers testestestest"
print containerstest['LIBS']

check_linked_list = containerstest.Program('linked_list.test', 
                    	         	   source = ['linked_list_test.c', 
				           	     '%s/linked_list.o' % containers_path
                                          	    ])
