import os

Import('commonsenv')

commons_path = os.getcwd() + '/../../'

#env.Append(
#    CPPPATH = ['#', commons_path, '/usr/include', '/usr/local/include', commons_path ],
#    LIBPATH = ['/usr/lib', '/usr/local/lib' ],
#    LIBS = ['check', 'curl', 'm', 'z'],
#    LINKFLAGS = [ '-openmp' ]
#)

containerstest = commonsenv.Clone()
containerstest['CPPPATH'] += [commons_path]
containerstest['LIBS'] += ['check', 'm', 'rt']

check_linked_list = containerstest.Program('linked_list.test', 
                    	         	   source = ['linked_list_test.c', 
				           	     '%s/containers/linked_list.o' % commons_path
                                          	    ])
