import os

Import('env', 'compiler', 'debug')

# Initialize environment
formats_env = env.Clone()
formats_env['objects'] = []


# Targets
formats = ['family', 'fastq', 'bam', 'gff', 'bed', 'ped', 'features', 'vcf', 'db']

for dir in formats:
    SConscript(os.path.join(dir, 'SConscript'), exports = ['env', 'formats_env', 'debug'])

formats_env.Library('bioformats', formats_env['objects'])

from pprint import pprint
print "EEEEeeeeeEEeeee bioformats objects"

print formats_env['objects']
#for key in formats_env:
  #  print key, 'corresponds to', formats_env[key]

env['objects'] += formats_env['objects']
