import os

Import('penv')

bioformats_path = os.getcwd() + '/../../../../bioformats/'
commons_path = os.getcwd() + '/../../../../commons/'

env = penv.Clone()
env.Append(
    LIBPATH = ['/usr/lib', '/usr/local/lib', '#libs', commons_path ],
    LIBS = ['check', 'common', 'curl', 'dl', 'm', 'rt', 'z'],
    LINKFLAGS = ['-fopenmp']
)


region = env.Program('region.test', 
                     source = ['test_region.c', 
                               "%s/libcommon.a" % commons_path,
                               "%s/libbioformats.a" % bioformats_path
                               ]
                    )

region_table = env.Program('region_table.test', 
                           source = ['test_region_table.c', 
                                     "%s/libcommon.a" % commons_path,
                                     "%s/libbioformats.a" % bioformats_path
                                    ]
                          )

parsing = env.Program('parse_regions_vcf.test', 
                      source = ['test_parse_regions.c', 
                                "%s/libcommon.a" % commons_path,
                                "%s/libbioformats.a" % bioformats_path
                               ]
                     )
