import os

print os.getcwd()

Import('aligners_env')

bwt_env = aligners_env.Clone()
bwt_env['objects'] = []

aligners_env['objects'] += aligners_env.Object(Split('bwt_commons.c'))

#print bwt_env['objects']

formats = ['csalib', 'dbwt', 'search', 'test']
for dir in formats:
    SConscript(os.path.join(dir, 'SConscript'), exports = ['aligners_env', 'bwt_env'])


# TODO: Remove fastq_batch_reader_omp so Glob can be used
#aligners_env['objects'] += penv.Object(Split('bwt.c bwt_bs.c BW_io.c BW_search.c BW_preprocess.c genome.c'))


aligners_env['CFLAGS'] += " -DFM_COMP_64 "
aligners_env['objects'] += aligners_env.Object(Split('genome.c bwt.c bwt_bs.c'))
