import os

Import('env', 'debug', 'compiler')

#New environment for commons
commonsenv = env.Clone()

# Initialize environment
commonsenv['objects'] = []
commonsenv.Decider('MD5-timestamp')

if debug == 1:
    commonsenv['CFLAGS'] += ' -O0 -g'
else:
    commonsenv['CFLAGS'] += ' -O3 '


# Compile argtable/ objects
argtableenv = commonsenv.Clone()
argtableenv['CFLAGS'] += ' -DHAVE_CONFIG_H -fPIC -DPIC'
argtableenv.Decider('MD5-timestamp')

if debug == 1:
    argtableenv['CFLAGS'] += ' -O0 -g'
else:
    argtableenv['CFLAGS'] += ' -O2 '


# Compile config/ objects
configenv = commonsenv.Clone()
configenv['CFLAGS'] += ' -DHAVE_CONFIG_H -D_REENTRANT -Wall -Wshadow -Wextra -Wdeclaration-after-statement -Wno-unused-parameter'
configenv.Decider('MD5-timestamp')

if debug == 1:
    configenv['CFLAGS'] += ' -O0 -g'
else:
    configenv['CFLAGS'] += ' -O2 '


# Targets
commons_obj = commonsenv.Object(Glob('./*.c'))
argtable_obj = argtableenv.Object(Glob('argtable/*.c'))
config_obj = configenv.Object(Glob('config/*.c'))

# Objects
commonsenv['objects'] += commons_obj + argtable_obj + config_obj

commonsenv.Library('common', commonsenv['objects'])

env['objects'] += commonsenv['objects']
